services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    ports:
      - "${REDIS_PORT:-6379}:6379"
      - "${REDIS_WEB_PORT:-8001}:8001"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  pgdata: